date = 2021-11-05
texte = "les touristes extra-europÃ©ens pourront convertir leur certificat de vaccination en pharmacie pour obtenir un pass sanitaire"
lien = "/pass-sanitaire-qr-code-voyages.html#j-ai-ete-vaccine-a-l-etranger-avec-un-vaccin-reconnu-en-france-comment-obtenir-un-qr-code-valable-en-france"
emoji = "ğŸŒ"
