date = 2021-12-22
texte = "la vaccination est dÃ©sormais possible pour les enfants de 5 Ã  11Â ans"
lien = "/conseils-pour-les-enfants.html#les-enfants-de-5-a-11-ans-peuvent-ils-etre-vaccines"
emoji = "ğŸ§’"
